// AUTO-GENERATED by scripts/generate-search-index.mjs — do not edit by hand.
// Pages are derived from the routes in App.tsx; content lives in
// scripts/data/search-content.json. Run `pnpm search:index` after changing either.

export type SearchType = 'page' | 'article' | 'book' | 'program' | 'event';

export interface SearchEntry {
  id: string;
  type: SearchType;
  title: string;
  excerpt: string;
  url: string;
  category: string;
  tags: string[];
}

export const SEARCH_INDEX: SearchEntry[] = [
  {
    "id": "p1",
    "type": "page",
    "title": "Home",
    "excerpt": "Sanatan International — a permanent Gurukul campus for the Indian diaspora in California.",
    "url": "/",
    "category": "Page",
    "tags": [
      "home",
      "sanatan",
      "international"
    ]
  },
  {
    "id": "p2",
    "type": "page",
    "title": "About the Centre",
    "excerpt": "Our founding story, values, and what makes the Centre different.",
    "url": "/about",
    "category": "Page",
    "tags": [
      "about",
      "story",
      "values"
    ]
  },
  {
    "id": "p3",
    "type": "page",
    "title": "The Hub",
    "excerpt": "About, vision, mission, founders and advisors in one place.",
    "url": "/hub",
    "category": "Page",
    "tags": [
      "hub",
      "about",
      "vision",
      "founders"
    ]
  },
  {
    "id": "p4",
    "type": "page",
    "title": "Vision & Mission",
    "excerpt": "A permanent campus for human flourishing — the why behind the work.",
    "url": "/vision",
    "category": "Page",
    "tags": [
      "vision",
      "mission",
      "purpose"
    ]
  },
  {
    "id": "p5",
    "type": "page",
    "title": "Founders & Advisors",
    "excerpt": "Meet the team and advisory board guiding the Centre.",
    "url": "/founders",
    "category": "Page",
    "tags": [
      "founders",
      "advisors",
      "team",
      "board"
    ]
  },
  {
    "id": "p6",
    "type": "page",
    "title": "Gurukul",
    "excerpt": "Gurukul-based education rooted in Vedic tradition, for every age and stage.",
    "url": "/gurukul",
    "category": "Page",
    "tags": [
      "gurukul",
      "education",
      "school"
    ]
  },
  {
    "id": "p7",
    "type": "page",
    "title": "Gurukul Foundation",
    "excerpt": "The foundation programme — the base of the four-level Gurukul curriculum.",
    "url": "/gurukul/foundation",
    "category": "Page",
    "tags": [
      "gurukul",
      "foundation",
      "curriculum"
    ]
  },
  {
    "id": "p8",
    "type": "page",
    "title": "Gurukul Programs",
    "excerpt": "Kids programmes and the adult ladder — every age, every stage, one path.",
    "url": "/gurukul/programs",
    "category": "Page",
    "tags": [
      "programs",
      "courses",
      "kids",
      "adults"
    ]
  },
  {
    "id": "p9",
    "type": "page",
    "title": "Digital Gurukul",
    "excerpt": "Live daily classes online — Sanskrit, yoga, Ayurveda and Vedic knowledge.",
    "url": "/gurukul/digital",
    "category": "Page",
    "tags": [
      "digital",
      "online",
      "live",
      "zoom",
      "classes"
    ]
  },
  {
    "id": "p10",
    "type": "page",
    "title": "Meta Gurukul",
    "excerpt": "The Meta Gurukul app — daily practice, tracking and community.",
    "url": "/gurukul/meta-gurukul",
    "category": "Page",
    "tags": [
      "meta gurukul",
      "app",
      "mobile"
    ]
  },
  {
    "id": "p11",
    "type": "page",
    "title": "Gurukul Ayurveda",
    "excerpt": "Ayurveda studies within the Gurukul — herbs, doshas and classical texts.",
    "url": "/gurukul/ayurveda",
    "category": "Page",
    "tags": [
      "ayurveda",
      "herbs",
      "health"
    ]
  },
  {
    "id": "p12",
    "type": "page",
    "title": "Join the Gurukul",
    "excerpt": "Enrolment — fees, schedule and how to apply.",
    "url": "/gurukul/join",
    "category": "Page",
    "tags": [
      "join",
      "enrol",
      "enroll",
      "apply",
      "admission",
      "fees"
    ]
  },
  {
    "id": "p13",
    "type": "page",
    "title": "Ayurveda Research",
    "excerpt": "Ayurveda research, herb studies and evidence-based preventive health.",
    "url": "/ayurveda",
    "category": "Page",
    "tags": [
      "ayurveda",
      "research",
      "herbs",
      "health"
    ]
  },
  {
    "id": "p14",
    "type": "page",
    "title": "Digital Welfare Suite",
    "excerpt": "Our apps — ethical technology built for human welfare.",
    "url": "/apps",
    "category": "Page",
    "tags": [
      "apps",
      "technology",
      "digital",
      "software"
    ]
  },
  {
    "id": "p15",
    "type": "page",
    "title": "Blog",
    "excerpt": "Research-backed writing on Ayurveda, education, dharma and the diaspora.",
    "url": "/blog",
    "category": "Page",
    "tags": [
      "blog",
      "articles",
      "writing",
      "newsroom"
    ]
  },
  {
    "id": "p16",
    "type": "page",
    "title": "Press & Media",
    "excerpt": "Press kit, media coverage and interview requests.",
    "url": "/press",
    "category": "Page",
    "tags": [
      "press",
      "media",
      "news",
      "journalist"
    ]
  },
  {
    "id": "p17",
    "type": "page",
    "title": "Impact",
    "excerpt": "Who we have reached and what has changed — measured outcomes.",
    "url": "/impact",
    "category": "Page",
    "tags": [
      "impact",
      "outcomes",
      "results"
    ]
  },
  {
    "id": "p18",
    "type": "page",
    "title": "FAQs",
    "excerpt": "Answers to the questions we are asked most often.",
    "url": "/faqs",
    "category": "Page",
    "tags": [
      "faq",
      "faqs",
      "questions",
      "help"
    ]
  },
  {
    "id": "p19",
    "type": "page",
    "title": "Contact",
    "excerpt": "Get in touch about enrolment, donations, volunteering or media.",
    "url": "/contact",
    "category": "Page",
    "tags": [
      "contact",
      "email",
      "address",
      "phone",
      "reach"
    ]
  },
  {
    "id": "p20",
    "type": "page",
    "title": "Volunteer",
    "excerpt": "Give time and skills — teaching, events, technology and outreach.",
    "url": "/volunteer",
    "category": "Page",
    "tags": [
      "volunteer",
      "help",
      "seva",
      "give time"
    ]
  },
  {
    "id": "p21",
    "type": "page",
    "title": "Events",
    "excerpt": "Satsangs, festivals, open days and the annual campus gala.",
    "url": "/events",
    "category": "Page",
    "tags": [
      "events",
      "calendar",
      "satsang",
      "festival"
    ]
  },
  {
    "id": "p22",
    "type": "page",
    "title": "Donate",
    "excerpt": "Support the Land Fund and the 33-acre campus.",
    "url": "/donate",
    "category": "Page",
    "tags": [
      "donate",
      "donation",
      "give",
      "fund",
      "support",
      "contribute"
    ]
  },
  {
    "id": "p23",
    "type": "page",
    "title": "Marketplace",
    "excerpt": "Organic essentials and authentic products — launching soon.",
    "url": "/marketplace",
    "category": "Page",
    "tags": [
      "marketplace",
      "shop",
      "store",
      "products"
    ]
  },
  {
    "id": "p24",
    "type": "page",
    "title": "Financial Reports",
    "excerpt": "Quarterly transparency reports with downloadable PDFs.",
    "url": "/financial-reports",
    "category": "Page",
    "tags": [
      "financial",
      "reports",
      "transparency",
      "accounts",
      "pdf"
    ]
  },
  {
    "id": "p25",
    "type": "page",
    "title": "Collaborations",
    "excerpt": "Partner institutions, universities and research collaborators.",
    "url": "/collaborations",
    "category": "Page",
    "tags": [
      "collaborations",
      "partners",
      "partnerships"
    ]
  },
  {
    "id": "p26",
    "type": "page",
    "title": "Campus Vision",
    "excerpt": "33-acre campus renders — Gurukul, yoga, Ayurveda gardens and farm.",
    "url": "/campus",
    "category": "Page",
    "tags": [
      "campus",
      "land",
      "renders",
      "building"
    ]
  },
  {
    "id": "p27",
    "type": "page",
    "title": "E-Books",
    "excerpt": "Digital books, audio books and video courses.",
    "url": "/ebooks",
    "category": "Page",
    "tags": [
      "ebooks",
      "books",
      "digital"
    ]
  },
  {
    "id": "p28",
    "type": "page",
    "title": "Books & Courses",
    "excerpt": "Digital books, audio books and video courses.",
    "url": "/books",
    "category": "Page",
    "tags": [
      "books",
      "ebooks",
      "courses",
      "library",
      "read"
    ]
  },
  {
    "id": "p29",
    "type": "page",
    "title": "Digital Scriptures",
    "excerpt": "Classical Sanskrit scriptures in digital format — coming soon.",
    "url": "/scriptures",
    "category": "Page",
    "tags": [
      "scriptures",
      "sanskrit",
      "texts",
      "vedas"
    ]
  },
  {
    "id": "p30",
    "type": "page",
    "title": "Privacy Policy",
    "excerpt": "How we handle personal data.",
    "url": "/privacy-policy",
    "category": "Page",
    "tags": [
      "privacy",
      "policy",
      "data",
      "legal"
    ]
  },
  {
    "id": "p31",
    "type": "page",
    "title": "Terms of Service",
    "excerpt": "The terms governing use of this site.",
    "url": "/terms-of-service",
    "category": "Page",
    "tags": [
      "terms",
      "service",
      "legal"
    ]
  },
  {
    "id": "p32",
    "type": "page",
    "title": "Cookie Policy",
    "excerpt": "How this site uses cookies.",
    "url": "/cookie-policy",
    "category": "Page",
    "tags": [
      "cookies",
      "policy",
      "legal"
    ]
  },
  {
    "id": "p33",
    "type": "page",
    "title": "Accessibility Statement",
    "excerpt": "Our accessibility commitments and how to report a barrier.",
    "url": "/accessibility",
    "category": "Page",
    "tags": [
      "accessibility",
      "a11y",
      "wcag",
      "legal"
    ]
  },
  {
    "id": "b1",
    "type": "article",
    "title": "Ashwagandha: What 5,000 Years of Ayurveda and Modern Science Agree On",
    "excerpt": "From the Charaka Samhita to peer-reviewed clinical trials — the evidence for Withania somnifera as an adaptogen, cortisol modulator, and cognitive enhancer.",
    "url": "/blog/ashwagandha-research-guide",
    "category": "Ayurveda",
    "tags": [
      "Ayurveda",
      "Herbs",
      "Research",
      "Ashwagandha"
    ]
  },
  {
    "id": "b2",
    "type": "article",
    "title": "The Neuroscience of Vedic Meditation: What Happens in the Brain After 40 Days",
    "excerpt": "A review of 200+ peer-reviewed studies on meditation, neuroplasticity, BDNF, HRV, and telomere length.",
    "url": "/blog/yoga-neuroscience-2026",
    "category": "Meditation",
    "tags": [
      "Meditation",
      "Neuroscience",
      "Yoga",
      "Research"
    ]
  },
  {
    "id": "b3",
    "type": "article",
    "title": "Shilajit: The Mountain Resin That Modern Science Is Finally Taking Seriously",
    "excerpt": "Fulvic acid, dibenzo-alpha-pyrones, and 84 trace minerals — the bioactive compounds in Shilajit and what the research says.",
    "url": "/blog/shilajit-research-guide",
    "category": "Ayurveda",
    "tags": [
      "Shilajit",
      "Ayurveda",
      "Herbs",
      "Research"
    ]
  },
  {
    "id": "b4",
    "type": "article",
    "title": "The Indian Diaspora Identity Crisis — And What Sanatan Dharma Offers",
    "excerpt": "Second-generation Indians in the US face a documented bicultural identity conflict. Here is what the research says — and what ancient wisdom offers.",
    "url": "/blog/diaspora-identity-crisis",
    "category": "Community",
    "tags": [
      "Diaspora",
      "Identity",
      "Culture",
      "Community"
    ]
  },
  {
    "id": "b5",
    "type": "article",
    "title": "Vedic Mathematics: Why Indian-American Students Are Rediscovering It",
    "excerpt": "The 16 Sutras, the research on calculation speed and mathematical confidence, and how to start teaching it to your children.",
    "url": "/blog/vedic-mathematics-guide",
    "category": "Education",
    "tags": [
      "Mathematics",
      "Vedic",
      "Education",
      "Children"
    ]
  },
  {
    "id": "b6",
    "type": "article",
    "title": "Digital Wellness Through Dharma: A Framework for Screen Time in Indian Families",
    "excerpt": "Brahmacharya, Ahimsa, and Svadhyaya as practical principles for managing technology use in the home.",
    "url": "/blog/digital-wellness-dharma",
    "category": "Wellness",
    "tags": [
      "Digital Wellness",
      "Technology",
      "Dharma",
      "Family"
    ]
  },
  {
    "id": "b7",
    "type": "article",
    "title": "The Gurukul Model: Why Ancient Education Beats Modern Schooling for Character Development",
    "excerpt": "A comparison of Gurukul-based education with modern schooling across character development, critical thinking, and cultural continuity.",
    "url": "/blog/gurukul-history-modern-education",
    "category": "Education",
    "tags": [
      "Gurukul",
      "Education",
      "History",
      "Children"
    ]
  },
  {
    "id": "b8",
    "type": "article",
    "title": "Bhagavad Gita as a Leadership Manual",
    "excerpt": "How Fortune 500 executives, military strategists, and management scholars are applying the Gita's 18 chapters to modern leadership.",
    "url": "/blog/bhagavad-gita-leadership",
    "category": "Philosophy",
    "tags": [
      "Bhagavad Gita",
      "Leadership",
      "Philosophy"
    ]
  },
  {
    "id": "bk1",
    "type": "book",
    "title": "Vedanta in the Modern Age",
    "excerpt": "A rigorous exploration of Advaita Vedanta philosophy and its direct applications to modern life — work, relationships, identity, and consciousness.",
    "url": "/books",
    "category": "Digital Book",
    "tags": [
      "Philosophy",
      "Vedanta",
      "Consciousness"
    ]
  },
  {
    "id": "bk2",
    "type": "book",
    "title": "The Gurukul Method",
    "excerpt": "Ancient education principles for modern children. How the Gurukul model develops character, wisdom, and capability.",
    "url": "/books",
    "category": "Digital Book",
    "tags": [
      "Education",
      "Parenting",
      "Gurukul"
    ]
  },
  {
    "id": "bk3",
    "type": "book",
    "title": "Ayurveda Decoded",
    "excerpt": "The science of longevity — from the Tridosha framework to Rasayana herbs, panchakarma, and daily routines.",
    "url": "/books",
    "category": "Digital Book",
    "tags": [
      "Ayurveda",
      "Health",
      "Herbs"
    ]
  },
  {
    "id": "bk4",
    "type": "book",
    "title": "The Living Yoga",
    "excerpt": "Breath, body, and consciousness — a complete audio guide to the living practice of yoga, from asana to samadhi.",
    "url": "/books",
    "category": "Audio Book",
    "tags": [
      "Yoga",
      "Pranayama",
      "Meditation"
    ]
  },
  {
    "id": "bk5",
    "type": "book",
    "title": "Dharma in Daily Life",
    "excerpt": "A 30-day video journey through the practical application of Dharmic principles — in work, relationships, parenting, and technology.",
    "url": "/books",
    "category": "Video Course",
    "tags": [
      "Dharma",
      "Lifestyle",
      "Philosophy"
    ]
  },
  {
    "id": "bk6",
    "type": "book",
    "title": "Sanskrit for Beginners",
    "excerpt": "Learn Sanskrit from zero to reading the Bhagavad Gita. Devanagari script, grammar, vocabulary, and classical texts.",
    "url": "/books",
    "category": "Video Course",
    "tags": [
      "Sanskrit",
      "Language",
      "Beginner"
    ]
  },
  {
    "id": "p1",
    "type": "program",
    "title": "Sanskrit & Vedic Studies",
    "excerpt": "Daily live classes in Sanskrit language, Vedic chanting, and classical texts. For children ages 5–18.",
    "url": "/gurukul/programs",
    "category": "Program",
    "tags": [
      "Sanskrit",
      "Vedic",
      "Children",
      "Education"
    ]
  },
  {
    "id": "p2",
    "type": "program",
    "title": "Yoga & Pranayama",
    "excerpt": "Classical Hatha Yoga, Pranayama, and meditation practice. Taught by credentialed instructors in the Iyengar tradition.",
    "url": "/gurukul/programs",
    "category": "Program",
    "tags": [
      "Yoga",
      "Pranayama",
      "Health",
      "Wellness"
    ]
  },
  {
    "id": "p3",
    "type": "program",
    "title": "Ayurveda & Wellness",
    "excerpt": "Practical Ayurveda for modern families — diet, lifestyle, seasonal routines, and herbal medicine.",
    "url": "/gurukul/programs",
    "category": "Program",
    "tags": [
      "Ayurveda",
      "Health",
      "Wellness",
      "Herbs"
    ]
  },
  {
    "id": "p4",
    "type": "program",
    "title": "Leadership & Dharma",
    "excerpt": "The Bhagavad Gita, Arthashastra, and Chanakya Niti as frameworks for ethical leadership and decision-making.",
    "url": "/gurukul/programs",
    "category": "Program",
    "tags": [
      "Leadership",
      "Dharma",
      "Philosophy",
      "Adults"
    ]
  },
  {
    "id": "p5",
    "type": "program",
    "title": "Digital Gurukul",
    "excerpt": "Live daily classes via Zoom — 20 minutes of ancient wisdom, every day. Sanskrit, Yoga, Ayurveda, and Vedic knowledge.",
    "url": "/gurukul/digital",
    "category": "Program",
    "tags": [
      "Digital",
      "Online",
      "Children",
      "Sanskrit"
    ]
  },
  {
    "id": "e1",
    "type": "event",
    "title": "Navaratri Satsang & Katha",
    "excerpt": "A 9-night celebration of the Divine Feminine — daily katha, bhajans, and community gathering. Open to all.",
    "url": "/events",
    "category": "Event",
    "tags": [
      "Navaratri",
      "Satsang",
      "Community",
      "Festival"
    ]
  },
  {
    "id": "e2",
    "type": "event",
    "title": "Yoga & Wellness Day",
    "excerpt": "A full-day outdoor yoga and wellness retreat — asana, pranayama, Ayurvedic cooking, and meditation. Families welcome.",
    "url": "/events",
    "category": "Event",
    "tags": [
      "Yoga",
      "Wellness",
      "Family",
      "Retreat"
    ]
  },
  {
    "id": "e3",
    "type": "event",
    "title": "Gurukul Open Day",
    "excerpt": "Visit the Gurukul, meet the teachers, and watch a live class. For families considering enrollment.",
    "url": "/events",
    "category": "Event",
    "tags": [
      "Gurukul",
      "Enrollment",
      "Family",
      "Education"
    ]
  },
  {
    "id": "e4",
    "type": "event",
    "title": "Annual Campus Fund Gala",
    "excerpt": "The annual fundraising gala for the 33-acre campus in El Sabrante, CA. Dinner, cultural performances, and campus presentation.",
    "url": "/events",
    "category": "Event",
    "tags": [
      "Campus",
      "Fundraiser",
      "Gala",
      "Community"
    ]
  }
];
