import { useState } from 'react';
import { IMAGE_MANIFEST } from '@/lib/imageManifest';

type NativeImgProps = React.ImgHTMLAttributes<HTMLImageElement>;

export interface ImageProps extends Omit<NativeImgProps, 'src' | 'alt' | 'loading'> {
  src: string;
  /** Required. Pass "" for purely decorative images so screen readers skip them. */
  alt: string;
  /**
   * Above-the-fold images (hero art, logo) load eagerly at high priority.
   * Everything else lazy-loads — the default.
   */
  priority?: boolean;
}

/**
 * Site-wide image wrapper. Handles the three things every <img> here was missing:
 *
 *  1. WebP — serves the smaller sibling generated by scripts/optimize-images.mjs,
 *     falling back to the original file if it fails to decode.
 *  2. Layout stability — pulls intrinsic width/height from the generated manifest
 *     so the browser reserves space before the bytes arrive (no layout shift).
 *  3. Graceful failure — a missing file renders a styled placeholder instead of
 *     the browser's broken-image icon.
 *
 * Deliberately renders a single <img> rather than <picture>, so dropping it into
 * existing flex/grid layouts doesn't change the DOM shape.
 */
export default function Image({ src, alt, priority = false, style, className, ...rest }: ImageProps) {
  const meta = IMAGE_MANIFEST[src];
  const webpSrc = meta?.webp ? src.replace(/\.(png|jpe?g)$/i, '.webp') : null;

  // Stage 0: webp (when available) → Stage 1: original → Stage 2: placeholder
  const [stage, setStage] = useState<0 | 1 | 2>(webpSrc ? 0 : 1);

  if (stage === 2) {
    return (
      <div
        className={className}
        style={{
          ...style,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          background: 'linear-gradient(135deg, var(--si-orange-tint) 0%, var(--si-orange-light) 100%)',
          color: 'var(--si-orange-ink)',
          minHeight: style?.minHeight ?? '48px',
        }}
        role="img"
        aria-label={alt || 'Image unavailable'}>
        <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true">
          <path d="M12 3c-1.6 2.2-2.4 4.4-2.4 6.6 0 2.2.8 4.4 2.4 6.6 1.6-2.2 2.4-4.4 2.4-6.6C14.4 7.4 13.6 5.2 12 3Z" />
          <path d="M12 16.2c-2.2-1.6-4.4-2.4-6.6-2.4 0 2.2 1.1 4 3.3 5.3 2.2 1.3 4.3 1.6 6.6 1.6 2.3 0 4.4-.3 6.6-1.6 2.2-1.3 3.3-3.1 3.3-5.3-2.2 0-4.4.8-6.6 2.4" />
        </svg>
      </div>
    );
  }

  return (
    <img
      src={stage === 0 && webpSrc ? webpSrc : src}
      alt={alt}
      className={className}
      style={style}
      width={meta?.w}
      height={meta?.h}
      loading={priority ? 'eager' : 'lazy'}
      decoding="async"
      fetchPriority={priority ? 'high' : undefined}
      onError={() => setStage((s) => (s === 0 ? 1 : 2))}
      {...rest}
    />
  );
}
