// Generates sitemap.xml, robots.txt and llms.txt from the real route table.
//
// The previous sitemap was hand-maintained and had drifted — 24 URLs against 33
// indexable routes, so nine pages were invisible to crawlers. Deriving it from
// App.tsx means it cannot go stale.
//
// llms.txt is the emerging convention for generative answer engines — a
// plain-text map of what the site covers, which is what
// actually gets cited. Costs nothing and is read by the crawlers that increasingly
// drive discovery.
import fs from 'node:fs';

const APP = 'client/src/App.tsx';
const SITE = 'https://www.sanataninternational.org';
const OUT_DIR = 'client/public';

// Priority and change cadence by section. Conversion pages rank above legal pages.
const TUNING = {
  '/': { p: '1.0', f: 'weekly' },
  '/donate': { p: '0.95', f: 'weekly' },
  '/gurukul/join': { p: '0.95', f: 'weekly' },
  '/gurukul': { p: '0.9', f: 'weekly' },
  '/gurukul/programs': { p: '0.9', f: 'weekly' },
  '/gurukul/digital': { p: '0.9', f: 'weekly' },
  '/hub': { p: '0.85', f: 'monthly' },
  '/campus': { p: '0.85', f: 'monthly' },
  '/blog': { p: '0.85', f: 'weekly' },
  '/events': { p: '0.85', f: 'weekly' },
  '/ayurveda': { p: '0.8', f: 'monthly' },
  '/books': { p: '0.8', f: 'monthly' },
  '/contact': { p: '0.8', f: 'monthly' },
  '/volunteer': { p: '0.8', f: 'monthly' },
  '/impact': { p: '0.75', f: 'monthly' },
  '/faqs': { p: '0.75', f: 'monthly' },
  '/press': { p: '0.7', f: 'monthly' },
  '/financial-reports': { p: '0.7', f: 'quarterly' },
  '/collaborations': { p: '0.7', f: 'monthly' },
};
const DEFAULT_TUNE = { p: '0.6', f: 'monthly' };

const NOINDEX = new Set([
  '/auth/signin', '/auth/signup', '/login', '/register',
  '/404', '/admin/submissions', '/dashboard', '/donate/success',
]);

const app = fs.readFileSync(APP, 'utf-8');
const routes = [...app.matchAll(/<Route\s+path="([^"]+)"/g)]
  .map((m) => m[1])
  .filter((r) => !r.includes(':') && !NOINDEX.has(r));

const today = process.env.SEO_DATE || new Date().toISOString().slice(0, 10);

// ── sitemap.xml ───────────────────────────────────────────────────────────────
const urls = routes
  .map((r) => {
    const t = TUNING[r] || DEFAULT_TUNE;
    return `  <url>
    <loc>${SITE}${r === '/' ? '/' : r}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${t.f}</changefreq>
    <priority>${t.p}</priority>
  </url>`;
  })
  .join('\n');

fs.writeFileSync(
  `${OUT_DIR}/sitemap.xml`,
  `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-seo.mjs from the routes in App.tsx. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`,
  'utf-8',
);

// ── robots.txt ────────────────────────────────────────────────────────────────
fs.writeFileSync(
  `${OUT_DIR}/robots.txt`,
  `# Sanatan International — www.sanataninternational.org

User-agent: *
Allow: /

# Not useful in search results
Disallow: /login
Disallow: /register
Disallow: /auth/
Disallow: /admin/
Disallow: /dashboard
Disallow: /donate/success
Disallow: /404

# Generative engines (AI answer engines and their crawlers) are welcome — being
# cited in AI answers is a discovery channel for a nonprofit, not a threat. They
# are covered by the wildcard rule above; no per-crawler rules are needed.

Sitemap: ${SITE}/sitemap.xml
`,
  'utf-8',
);

// ── llms.txt ──────────────────────────────────────────────────────────────────
const SECTIONS = {
  'About the organisation': ['/', '/hub', '/about', '/vision', '/founders', '/impact', '/campus'],
  'Gurukul education': ['/gurukul', '/gurukul/foundation', '/gurukul/programs', '/gurukul/digital', '/gurukul/meta-gurukul', '/gurukul/ayurveda', '/gurukul/join'],
  'Ayurveda & research': ['/ayurveda'],
  'Reading & media': ['/blog', '/books', '/ebooks', '/press', '/scriptures'],
  'Get involved': ['/donate', '/volunteer', '/events', '/contact', '/collaborations'],
  'Governance & policies': ['/financial-reports', '/privacy-policy', '/terms-of-service', '/cookie-policy', '/accessibility'],
  Other: [],
};

let index;
try {
  index = JSON.parse(
    fs.readFileSync('client/src/lib/searchIndex.ts', 'utf-8').split('SEARCH_INDEX: SearchEntry[] = ')[1].replace(/;\s*$/, ''),
  );
} catch {
  index = [];
}
const descOf = (r) => (index.find((e) => e.url === r && e.type === 'page') || {}).excerpt || '';

const claimed = new Set(Object.values(SECTIONS).flat());
SECTIONS.Other = routes.filter((r) => !claimed.has(r));

const body = Object.entries(SECTIONS)
  .filter(([, rs]) => rs.some((r) => routes.includes(r)))
  .map(([heading, rs]) => {
    const items = rs
      .filter((r) => routes.includes(r))
      .map((r) => `- [${(index.find((e) => e.url === r && e.type === 'page') || {}).title || r}](${SITE}${r}): ${descOf(r)}`)
      .join('\n');
    return `## ${heading}\n\n${items}`;
  })
  .join('\n\n');

fs.writeFileSync(
  `${OUT_DIR}/llms.txt`,
  `# Sanatan International

> A registered 501(c)(3) public-benefit organisation in El Sobrante, California,
> building a permanent 33-acre Gurukul campus for the Indian diaspora. The
> organisation works across four areas: Gurukul-based education, Ayurveda research
> and preventive health, ethical technology for human welfare, and sustainable
> indigenous production.

Founded 2024. Serving the San Francisco Bay Area — Oakland, San Jose, Fremont,
Santa Clara, Richmond — and the global Indian diaspora. Teaching languages:
English, Hindi, Sanskrit.

${body}

## Contact

- General: info@sanataninternational.org
- Donations: donate@sanataninternational.org
- Gurukul enrolment: gurukul@sanataninternational.org
- Press: press@sanataninternational.org
`,
  'utf-8',
);

console.log(`sitemap.xml  ${routes.length} urls`);
console.log(`robots.txt   written (generative crawlers allowed)`);
console.log(`llms.txt     ${Object.keys(SECTIONS).length} sections`);
